# Generated by Django 5.2.15 on 2026-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.TextField(blank=True, default=''),
        ),
    ]
